/* =============================================================================
   650 — COUNTRY-SPECIFIC GOVERNING (v1)
   -----------------------------------------------------------------------------
   Full governing terms for the international electoral systems. When you win an
   election abroad and take office, the crisis deck is drawn from the country you
   actually govern — US debt-ceiling showdowns, Weimar street violence, the
   French 49.3, Japan's ageing crisis, a one-party state's Five-Year Plan, and so
   on — all in English, all using your drafted cabinet's ministers for the
   gambles. Meter effects (approval / economy / unity) and career carry-over
   (voteShift / repShift) work exactly as the UK deck does.

   Loaded after govern.js (which owns G.EVENTS and the term engine), before ui.js.
   ============================================================================= */
window.G = window.G || {};

(function () {
  var G = window.G;

  /* compact builders ------------------------------------------------------- */
  function gmb(stat, dept, sa, se, su, fa, fe, fu) {
    return { stat: stat, dept: dept, success: { a: sa, e: se, u: su }, fail: { a: fa, e: fe, u: fu } };
  }
  function ch(label, text, a, e, u, vote, rep, gamble) {
    var c = { label: label, text: text, base: { a: a, e: e, u: u },
              careerEffect: { voteShift: vote, repShift: rep } };
    if (gamble) c.gamble = gamble;
    return c;
  }
  function ev(id, dept, title, icon, text, choices) {
    return { id: id, dept: dept, title: title, icon: icon, text: text, choices: choices };
  }

  G.COUNTRY_EVENTS = {

    /* ===================================================== UNITED STATES === */
    usa: [
      ev("usa_debt", "chancellor", "The Debt Ceiling", "$",
        "The Treasury will hit the borrowing limit in three weeks. Congress is dug in and a default would shake the world.",
        [ ch("Strike a bipartisan deal", "Trade spending caps for the votes.", 3, 4, -1, 0.010, 4),
          ch("Refuse to negotiate", "Dare the other side to own the default.", -2, 1, 4, -0.004, 0, gmb("statecraft","chancellor", 5,6,3, -8,-12,-4)),
          ch("Mint your way around it", "An exotic workaround the lawyers hate.", -4, -3, -2, -0.008, -3) ]),
      ev("usa_scotus", "justice", "A Supreme Court Vacancy", "§",
        "A justice has died. Your nominee will shape the law for a generation — and define the rest of your term.",
        [ ch("Nominate a firebrand", "Energise the base, enrage the other half.", 2, 0, 5, 0.008, 2, gmb("statecraft","justice", 4,0,4, -6,0,-5)),
          ch("Pick a consensus moderate", "Confirmable, forgettable, safe.", 3, 0, -2, 0.006, 3),
          ch("Leave the seat empty for now", "Bank it as a campaign issue.", -3, 0, 1, -0.004, -1) ]),
      ev("usa_guns", "home", "After the Shooting", "✚",
        "Another mass shooting fills the networks. The country demands you do something; half of it demands you do nothing.",
        [ ch("Push gun-control legislation", "Spend capital on background checks.", 4, -1, -3, 0.008, 3, gmb("oratory","pm", 5,0,2, -5,0,-4)),
          ch("Fund mental health and security", "The both-sides answer.", 1, -2, 1, 0.002, 1),
          ch("Defend the Second Amendment", "Stand with the gun lobby.", -3, 0, 3, -0.006, -2) ]),
      ev("usa_shutdown", "whip", "Government Shutdown", "▦",
        "Appropriations have stalled. At midnight the federal government goes dark and 800,000 workers go unpaid.",
        [ ch("Cave to keep it open", "Swallow their riders to end the pain.", 2, 2, -4, 0.004, 1),
          ch("Hold the line and shut it down", "A test of nerve nobody wins cleanly.", -5, -4, 3, -0.006, -1, gmb("partyMgmt","whip", 4,2,5, -9,-6,-4)),
          ch("Pass a stopgap and punt", "A short bill that solves nothing.", 0, 0, 0, 0.0, 0) ]),
      ev("usa_border", "home", "The Southern Border", "⚓",
        "Crossings hit a record and the governors are busing migrants to your front door.",
        [ ch("Surge enforcement and the wall", "Hard-line and unmistakable.", 4, -2, -1, 0.010, -1),
          ch("Comprehensive reform deal", "Pair the border with a path to status.", 0, 0, 0, 0.004, 3, gmb("statecraft","home", 6,1,3, -5,-1,-4)),
          ch("Expand legal pathways", "Lead with humanity and the courts.", -4, 0, 2, -0.008, 3) ]),
      ev("usa_tariffs", "business", "Tariffs on China", "⚖",
        "Your trade hawks want sweeping tariffs. Farmers and importers warn of a costly trade war.",
        [ ch("Slap on the tariffs", "Talk tough on Beijing.", 3, -4, 2, 0.008, 1),
          ch("Targeted, negotiated pressure", "Squeeze strategic sectors only.", 1, 1, 0, 0.004, 3, gmb("statecraft","foreign", 4,5,1, -4,-5,-2)),
          ch("Keep markets open", "Bet on cheaper goods at the till.", -2, 4, -1, -0.004, 1) ]),
      ev("usa_storm", "pm", "A Category 5", "🌀",
        "A monster hurricane levels a coastal state. The federal response will be on every screen for a week.",
        [ ch("Lead a massive federal response", "Be everywhere, spend big.", 6, -5, 1, 0.012, 4),
          ch("Let the states take the lead", "Stand back, send what's asked.", -3, 1, 0, -0.006, -2),
          ch("Tour the wreckage personally", "Optics are a policy.", 2, -1, 0, 0.004, 1, gmb("oratory","pm", 4,0,1, -5,0,-2)) ]),
      ev("usa_war", "defence", "Boots on the Ground?", "✈",
        "An ally is attacked and the Pentagon has drawn up options. The country is weary of foreign wars.",
        [ ch("Commit decisive force", "Shock, awe, and an open-ended bill.", 2, -6, 2, 0.006, 2, gmb("statecraft","defence", 6,-2,3, -7,-6,-4)),
          ch("Lead a coalition, no ground troops", "Air power and allies.", 3, -2, 1, 0.008, 3),
          ch("Stay out of it", "No more forever wars.", -2, 2, -1, -0.004, 0) ]),
      ev("usa_health", "health", "Healthcare Reckoning", "✚",
        "Premiums are spiking and the system creaks. Reform is a third rail you keep being handed.",
        [ ch("Expand public coverage", "Big, popular, and ferociously opposed.", 5, -5, -2, 0.010, 4, gmb("statecraft","health", 6,-2,2, -6,-3,-4)),
          ch("Shore up the existing markets", "Stabilise, don't overhaul.", 2, -1, 1, 0.004, 2),
          ch("Hand it to the states", "Let the laboratories of democracy sort it.", -2, 1, 0, -0.004, -1) ]),
      ev("usa_scandal", "whip", "A West Wing Scandal", "!",
        "A senior official is caught in a damaging mess. The press has the documents.",
        [ ch("Demand the resignation", "Cut and move on.", 2, 0, -3, 0.004, 1),
          ch("Stand by your appointee", "Loyalty, and the cost of it.", -5, 0, 3, -0.010, -6),
          ch("Appoint a special counsel", "Outsource the bleeding.", -1, 0, 0, -0.004, -1, gmb("oratory","pm", 3,0,1, -4,0,-2)) ])
    ],

    /* ====================================================== WEIMAR 1930s === */
    weimar: [
      ev("wmr_inflation", "chancellor", "The Mark in Freefall", "₰",
        "Prices double weekly. Workers are paid twice a day and spend it before nightfall.",
        [ ch("Issue a new, backed currency", "A desperate gamble to restore faith.", 2, 6, 1, 0.008, 4, gmb("statecraft","chancellor", 6,10,3, -7,-12,-4)),
          ch("Print to pay the bills", "Buy a week, sell the future.", 5, -8, 0, 0.004, -3),
          ch("Brutal austerity", "Slash spending; the streets will burn.", -7, 5, -3, -0.008, 1) ]),
      ev("wmr_street", "home", "Street Battles", "✊",
        "Communist and nationalist militias fight pitched battles in the cities. The police are overwhelmed.",
        [ ch("Ban the paramilitaries", "Outlaw the uniforms on every side.", 1, 0, -2, 0.004, 2, gmb("statecraft","home", 5,1,4, -6,-2,-5)),
          ch("Lean on the army to restore order", "Soldiers on the streets.", 3, 0, -3, 0.002, -1),
          ch("Tolerate 'patriotic' marchers", "Look the other way for one side.", -4, 0, 4, -0.010, -5) ]),
      ev("wmr_reparations", "foreign", "The Reparations Bill", "₤",
        "The Allies demand the next payment. The nation seethes at the Versailles yoke.",
        [ ch("Negotiate a moratorium", "Plead for breathing room abroad.", 2, 4, 1, 0.008, 3, gmb("statecraft","foreign", 5,6,2, -4,-6,-3)),
          ch("Pay, and keep the peace", "Honour the treaty, swallow the rage.", -4, -3, 0, -0.006, 1),
          ch("Refuse to pay", "Defy them and dare the consequences.", 5, -5, 3, 0.006, -2) ]),
      ev("wmr_unemployment", "business", "Six Million Idle", "⚙",
        "Unemployment is catastrophic. Soup kitchens stretch round the block.",
        [ ch("A vast public-works scheme", "Autobahns and jobs, paid somehow.", 5, 2, 1, 0.010, 4, gmb("statecraft","business", 6,6,2, -5,-6,-3)),
          ch("Wait for the market to clear", "Orthodox, and politically lethal.", -6, 3, -2, -0.010, 0),
          ch("Emergency relief payments", "Feed people now, find the money later.", 4, -4, 0, 0.006, 2) ]),
      ev("wmr_coalition", "whip", "The Coalition Splinters", "▤",
        "Your fragile Reichstag bloc is fracturing. A vote of no confidence looms.",
        [ ch("Buy off a wavering party", "Cabinet seats for survival.", 1, -1, 4, 0.004, 1),
          ch("Govern by emergency decree", "Article 48 — rule without them.", -3, 1, -4, -0.006, -3, gmb("statecraft","pm", 4,1,3, -7,-2,-7)),
          ch("Call their bluff", "Dare the chamber to bring you down.", -2, 0, 2, -0.004, 0, gmb("partyMgmt","whip", 4,0,5, -8,0,-8)) ]),
      ev("wmr_decree", "pm", "Rule by Decree", "§",
        "The chamber is paralysed. The President will sign emergency decrees if you ask — bypassing democracy itself.",
        [ ch("Govern through the President", "Effective, and corrosive to the republic.", 2, 2, -5, 0.002, -2),
          ch("Insist on parliamentary votes", "Slow, principled, perhaps doomed.", -3, -2, 4, 0.0, 3, gmb("oratory","pm", 4,0,5, -5,-2,-4)),
          ch("Call fresh elections", "Throw the dice with a furious electorate.", -2, 0, 0, -0.008, 0) ]),
      ev("wmr_army", "defence", "The Generals' Loyalty", "⚔",
        "The Reichswehr's commanders make clear their support is conditional. They want a free hand and more men.",
        [ ch("Indulge the army", "Concede to keep their bayonets onside.", 1, -3, 3, 0.004, -1),
          ch("Assert civilian control", "Remind them who governs.", -2, 0, -2, 0.002, 4, gmb("statecraft","defence", 4,0,3, -7,-2,-5)),
          ch("Play factions against each other", "Divide the high command.", 0, 0, 1, -0.002, -2, gmb("partyMgmt","defence", 3,0,3, -5,-1,-4)) ]),
      ev("wmr_press", "justice", "The Agitators' Press", "❡",
        "Extremist newspapers pour petrol on every crisis. Calls grow to silence them.",
        [ ch("Censor the worst offenders", "Curb the lies, bruise free speech.", 1, 0, -2, 0.002, 0, gmb("statecraft","justice", 4,0,3, -5,0,-4)),
          ch("Defend a free press", "Principle in a burning house.", -3, 0, 3, -0.004, 4),
          ch("Plant your own propaganda", "Fight fire with fire.", 2, 0, -1, 0.004, -3) ]),
      ev("wmr_demagogue", "leader", "The Demagogue Rises", "▲",
        "A spellbinding extremist draws vast crowds, promising to tear it all down. Some urge you to bring him inside the tent.",
        [ ch("Offer him a junior post", "Tame him with responsibility, you hope.", 3, 0, 2, 0.006, -4, gmb("statecraft","leader", 5,0,4, -9,0,-8)),
          ch("Confront and expose him", "Take the argument to the country.", -2, 0, 1, -0.002, 5, gmb("oratory","pm", 6,0,4, -7,0,-5)),
          ch("Ban his movement outright", "Provoke the storm to end it.", -4, -2, -2, -0.006, 1) ]),
      ev("wmr_communists", "home", "The Red Threat", "★",
        "A general strike and talk of revolution grip the industrial cities.",
        [ ch("Crack down hard", "Arrests, bans, and barricades.", 0, 1, -1, 0.004, -1, gmb("statecraft","home", 4,2,3, -6,-2,-5)),
          ch("Address the grievances", "Wages and bread cool tempers.", 4, -3, 1, 0.006, 3),
          ch("Let it burn out", "Gamble that the moment passes.", -3, -1, -2, -0.006, -2) ])
    ],

    /* ============================================== GERMANY (modern) ====== */
    germany: [
      ev("de_coalition", "whip", "The Coalition Wobbles", "▤",
        "Your junior partner threatens to walk over a flagship bill. Three-party government is exhausting.",
        [ ch("Concede to keep them in", "Water the bill to save the marriage.", 1, 0, 4, 0.004, 1),
          ch("Dare them to collapse it", "Call the partner's bluff.", -2, 0, -3, -0.004, 0, gmb("partyMgmt","whip", 4,1,5, -7,-1,-6)),
          ch("Reshuffle to reset the mood", "Fresh faces, new start.", 2, 0, 1, 0.004, 2, gmb("statecraft","pm", 3,0,4, -3,0,-4)) ]),
      ev("de_energy", "business", "The Energiewende", "⚡",
        "The green transition is costly and the grid is strained. Industry warns of an exodus.",
        [ ch("Accelerate renewables", "Subsidise wind and solar hard.", 3, -4, 1, 0.008, 3, gmb("statecraft","business", 5,3,2, -4,-5,-3)),
          ch("Slow down and protect industry", "Cheaper power, greener critics.", -2, 3, 0, -0.004, -2),
          ch("Extend the nuclear plants", "Break a taboo to keep the lights on.", 1, 4, -3, 0.004, 1) ]),
      ev("de_gas", "foreign", "Russian Gas", "🔥",
        "Half your heating depends on a hostile supplier. Security and the gas bill pull opposite ways.",
        [ ch("Cut the dependency fast", "Pay more now for sovereignty.", 2, -5, 2, 0.008, 4, gmb("statecraft","foreign", 5,-1,3, -4,-6,-3)),
          ch("Keep buying for now", "Cheap warmth, strategic shame.", -3, 4, -1, -0.006, -2),
          ch("Build LNG terminals at speed", "A scramble for alternatives.", 1, 0, 1, 0.004, 2) ]),
      ev("de_debtbrake", "chancellor", "The Debt Brake", "§",
        "The constitution caps borrowing. Investment is screaming for cash the rules forbid.",
        [ ch("Find a special fund", "A legal workaround for big spending.", 3, 2, -1, 0.006, 2, gmb("statecraft","chancellor", 5,5,1, -5,-4,-3)),
          ch("Respect the brake", "Fiscal virtue, starved investment.", -2, 2, 1, -0.002, 2),
          ch("Reform the rule itself", "A constitutional fight for headroom.", 1, 0, -3, 0.004, 1) ]),
      ev("de_migration", "home", "Migration Pressure", "⚓",
        "Arrivals climb and the states demand help. The far right is feasting on the issue.",
        [ ch("Tighten the rules", "Faster returns, harder borders.", 4, -1, -2, 0.008, -1),
          ch("A managed European deal", "Share the load across the EU.", 1, 0, 1, 0.004, 3, gmb("statecraft","foreign", 5,1,3, -4,-1,-3)),
          ch("Lead with integration", "Invest in welcome over walls.", -4, -2, 2, -0.008, 3) ]),
      ev("de_afd", "whip", "The Firewall", "▲",
        "The far right surges in the polls. Some in your camp whisper about cooperation at the local level.",
        [ ch("Hold the firewall absolutely", "No deals, no exceptions.", 1, 0, 3, 0.004, 4),
          ch("Co-opt their voters' issues", "Steal the thunder, risk the soul.", 3, 0, -2, 0.006, -3, gmb("statecraft","pm", 4,0,2, -5,0,-4)),
          ch("Quietly tolerate a local pact", "A line crossed in the shadows.", -3, 0, -3, -0.008, -5) ]),
      ev("de_nato", "defence", "NATO Demands More", "⚔",
        "Allies want you to hit the spending target. The pacifist instinct runs deep at home.",
        [ ch("Hit the 2% and rearm", "Reassure allies, spend big.", 1, -5, 1, 0.006, 3),
          ch("A phased build-up", "Promise the trajectory, not the shock.", 0, -2, 0, 0.004, 2, gmb("statecraft","defence", 4,0,2, -3,-2,-3)),
          ch("Resist the pressure", "Guns can wait; butter cannot.", -2, 3, 0, -0.004, -2) ]),
      ev("de_auto", "business", "The Car Industry Stalls", "⚙",
        "The mighty car sector is losing the electric race to China and California. Jobs are on the line.",
        [ ch("Subsidise the EV pivot", "Public billions for private wheels.", 3, -3, 0, 0.008, 3, gmb("statecraft","business", 5,4,1, -4,-5,-2)),
          ch("Protect combustion jobs", "Slow the transition to save towns.", 1, 1, 1, 0.002, -1),
          ch("Let the market decide", "No bailouts, brutal honesty.", -4, 2, -1, -0.006, 0) ]),
      ev("de_pension", "health", "The Pension Time Bomb", "⏳",
        "An ageing nation, a shrinking workforce, and a promise that no longer adds up.",
        [ ch("Raise the retirement age", "Necessary, detested.", -5, 5, -2, -0.008, 2),
          ch("Top it up from the budget", "Kick the cost to the taxpayer.", 4, -4, 1, 0.006, 1),
          ch("Build a sovereign pension fund", "Invest now for the demographic wave.", 0, 1, 0, 0.004, 3, gmb("statecraft","chancellor", 4,4,1, -3,-3,-2)) ]),
      ev("de_eu", "foreign", "A Crisis in Brussels", "★",
        "The EU is split on a bailout and everyone looks to Berlin to lead — and to pay.",
        [ ch("Lead and underwrite the deal", "European duty, German cheque.", 2, -4, 0, 0.006, 4, gmb("statecraft","foreign", 6,-1,2, -4,-5,-3)),
          ch("Demand strict conditions", "Solidarity with strings.", 0, 1, 1, 0.002, 1),
          ch("Block it to protect taxpayers", "Popular at home, isolated abroad.", -2, 2, -1, -0.004, -2) ])
    ],

    /* ====================================================== FRANCE ======== */
    france: [
      ev("fr_pension", "chancellor", "Pension Reform", "⏳",
        "You must raise the retirement age. The unions promise to bring the country to a halt.",
        [ ch("Force it through with 49.3", "Bypass the vote, own the fury.", -6, 4, -3, -0.006, 2, gmb("statecraft","pm", 4,4,2, -8,-2,-6)),
          ch("Negotiate with the unions", "Concessions to buy calm.", 3, -3, 2, 0.006, 2),
          ch("Withdraw the reform", "Retreat and save the streets.", 4, -5, 0, 0.004, -3) ]),
      ev("fr_gilets", "home", "Yellow Vests", "🦺",
        "A fuel-tax revolt becomes a leaderless national uprising. Roundabouts blaze every weekend.",
        [ ch("Scrap the tax and spend", "A costly climb-down to cool the anger.", 5, -5, 0, 0.008, 1),
          ch("A grand national debate", "Listen for months, decide little.", 1, -1, 1, 0.002, 2, gmb("oratory","pm", 5,0,2, -4,0,-3)),
          ch("Restore order firmly", "Police lines and live coverage.", -4, 1, 2, -0.006, -2) ]),
      ev("fr_laicite", "justice", "Laïcité", "§",
        "A row over religious symbols in schools tests the republic's secular creed.",
        [ ch("Enforce strict secularism", "The republican line, hard.", 2, 0, 2, 0.006, 1),
          ch("A pragmatic accommodation", "Quiet compromise over principle.", 0, 0, -1, 0.002, 2, gmb("statecraft","justice", 4,0,3, -4,0,-3)),
          ch("Defend religious freedom", "Liberty over uniformity.", -2, 0, 1, -0.004, 1) ]),
      ev("fr_eu", "foreign", "Leading Europe", "★",
        "With Berlin distracted, Paris can seize the wheel of the Union — if you're willing to spend the capital.",
        [ ch("Push a bold federal vision", "A European army, a shared budget.", 2, -2, 1, 0.008, 4, gmb("statecraft","foreign", 6,1,2, -5,-3,-3)),
          ch("Defend French interests first", "La France d'abord, politely.", 1, 1, 1, 0.004, 1),
          ch("Keep your head down", "Let others lead and blame.", -2, 0, -1, -0.004, -2) ]),
      ev("fr_banlieue", "home", "The Suburbs Burn", "🔥",
        "A death in police custody sparks nights of rioting across the banlieues.",
        [ ch("Deploy and impose curfews", "Force first, questions later.", 1, -1, 2, 0.004, -1, gmb("statecraft","home", 4,0,3, -6,-2,-4)),
          ch("Reform policing and invest", "Address the long grievance.", 2, -3, 0, 0.006, 3),
          ch("Promise both order and renewal", "Walk the impossible line.", 0, -1, 1, 0.002, 1) ]),
      ev("fr_farmers", "business", "The Farmers' Blockade", "🚜",
        "Tractors ring Paris. Farmers say EU rules and cheap imports are ruining them.",
        [ ch("Subsidies and protections", "Open the cheque book for the land.", 4, -4, 1, 0.008, 2),
          ch("Fight their corner in Brussels", "Promise to bend the EU rules.", 2, -1, 0, 0.004, 3, gmb("statecraft","foreign", 4,1,2, -3,-2,-3)),
          ch("Hold firm on free trade", "Consumers over producers.", -4, 3, -1, -0.006, -1) ]),
      ev("fr_nuclear", "business", "EDF and the Reactors", "⚡",
        "The nuclear fleet — your energy crown jewel — needs vast investment to keep France powered and exporting.",
        [ ch("Build a new generation", "Bet billions on the atom.", 2, 2, 0, 0.006, 3, gmb("statecraft","business", 5,5,1, -4,-4,-2)),
          ch("Patch the ageing fleet", "Cheaper now, riskier later.", 0, 1, 0, 0.002, 0),
          ch("Diversify into renewables", "Hedge the nuclear bet.", 1, -2, 1, 0.004, 1) ]),
      ev("fr_sahel", "defence", "The Sahel", "✈",
        "French troops are bogged down in West Africa and juntas are turning hostile.",
        [ ch("Withdraw the troops", "Cut the losses, lose the influence.", 2, 2, -1, 0.004, 1),
          ch("Reinforce the mission", "Double down on a hard fight.", -2, -4, 2, -0.004, 0, gmb("statecraft","defence", 4,-1,3, -6,-4,-3)),
          ch("Pivot to training and aid", "A lighter footprint.", 1, 0, 0, 0.002, 2) ]),
      ev("fr_4923", "whip", "Article 49.3", "▦",
        "Your budget can't pass the fractured Assembly. The constitution lets you force it — and invite a censure motion.",
        [ ch("Invoke 49.3", "Ram it through, brace for censure.", -3, 3, -2, -0.004, 1, gmb("partyMgmt","whip", 5,2,4, -8,-2,-6)),
          ch("Carve out a compromise", "Trade clauses for votes.", 2, -1, 2, 0.004, 2),
          ch("Drop the contested measures", "A thinner bill, a calmer house.", 0, -1, 1, 0.0, 0) ]),
      ev("fr_cohab", "leader", "Cohabitation Tension", "▲",
        "A rival power centre — a hostile majority or an ambitious premier — contests your authority daily.",
        [ ch("Assert presidential primacy", "Remind them where power sits.", 1, 0, -2, 0.004, 1, gmb("statecraft","leader", 4,0,3, -5,0,-4)),
          ch("Share power gracefully", "Govern by uneasy duet.", 0, 1, 2, 0.002, 2),
          ch("Dissolve and call elections", "Roll the dice for a clean mandate.", -1, 0, 0, -0.006, 0) ])
    ],

    /* ===================================================== AUSTRALIA ====== */
    australia: [
      ev("au_fires", "home", "Black Summer", "🔥",
        "Catastrophic bushfires consume whole towns. The nation wants leadership and answers on climate.",
        [ ch("Lead a huge relief effort", "Be present, spend, rebuild.", 6, -5, 1, 0.012, 4),
          ch("Link it to climate action", "Name the cause, anger the base.", 1, -2, -2, 0.004, 2, gmb("oratory","pm", 5,0,1, -5,0,-4)),
          ch("Focus on hazard reduction", "Practical, and quietly evasive.", -2, 0, 1, -0.004, -1) ]),
      ev("au_mining", "business", "The Mining Boom", "⛏",
        "Resource giants want new approvals; the Greens and the world want them stopped.",
        [ ch("Approve the megamine", "Jobs and royalties over carbon.", 3, 5, -3, 0.008, 1),
          ch("Block it on climate grounds", "Principle over the pit.", -3, -3, 3, -0.006, 3),
          ch("Approve with strict conditions", "Thread the needle.", 0, 2, 0, 0.002, 1, gmb("statecraft","business", 4,4,2, -3,-3,-2)) ]),
      ev("au_china", "foreign", "Beijing Bites Back", "★",
        "China slaps tariffs on your wine, barley and coal after a diplomatic spat.",
        [ ch("Stand firm and diversify", "Find new markets, hold the line.", 2, -3, 2, 0.008, 3, gmb("statecraft","foreign", 5,2,2, -4,-5,-3)),
          ch("Quietly mend fences", "Pragmatism over pride.", 1, 3, -1, 0.004, 1),
          ch("Escalate the rhetoric", "Play the tough guy.", -1, -2, 3, -0.004, -1) ]),
      ev("au_boats", "home", "Stop the Boats", "⚓",
        "Asylum vessels appear on the horizon and the issue dominates talkback radio.",
        [ ch("Hard-line turnbacks", "Offshore processing, no exceptions.", 4, -1, 0, 0.010, -1),
          ch("A regional resettlement deal", "Share the burden with neighbours.", 0, 0, 1, 0.004, 3, gmb("statecraft","foreign", 4,1,3, -4,-1,-3)),
          ch("A more humane policy", "Compassion at a political cost.", -4, 0, 2, -0.008, 3) ]),
      ev("au_voice", "justice", "A Referendum", "§",
        "You've promised a referendum on Indigenous recognition. The campaign is turning bitter.",
        [ ch("Campaign hard for Yes", "Spend your standing on the cause.", 2, 0, 1, 0.006, 4, gmb("oratory","pm", 5,0,3, -6,0,-4)),
          ch("Stay neutral and let it run", "Above the fray, or absent.", -2, 0, -1, -0.004, -2),
          ch("Quietly hope it fails", "Duck the fight you started.", -3, 0, -2, -0.006, -3) ]),
      ev("au_aukus", "defence", "AUKUS Submarines", "⚓",
        "The nuclear-submarine deal will cost a fortune over decades. Allies cheer; the budget groans.",
        [ ch("Commit fully", "Tie yourself to the alliance for a generation.", 1, -5, 2, 0.006, 3),
          ch("Renegotiate the terms", "Demand more local jobs and value.", 0, -1, 0, 0.004, 2, gmb("statecraft","defence", 4,0,2, -3,-2,-3)),
          ch("Scale it back", "Cheaper boats, cooler allies.", -2, 3, -1, -0.004, -2) ]),
      ev("au_drought", "business", "The Big Dry", "☀",
        "A historic drought empties the rivers and the bush is on its knees.",
        [ ch("A drought relief package", "Cash and water for the farmers.", 4, -4, 1, 0.008, 2),
          ch("Reform water rights", "Pick a fight over a finite resource.", -2, 1, -2, -0.004, 1, gmb("statecraft","business", 4,2,2, -4,-2,-3)),
          ch("Pray for rain and wait", "Hope is not a strategy.", -3, 1, -1, -0.006, -2) ]),
      ev("au_housing", "business", "Housing Out of Reach", "⌂",
        "A generation is locked out of home ownership. Negative gearing is the third rail.",
        [ ch("Build social housing at scale", "Public spades in the ground.", 4, -3, -1, 0.008, 3, gmb("statecraft","business", 5,3,1, -4,-4,-2)),
          ch("Touch negative gearing", "Brave the landlords' wrath.", -3, 2, -2, -0.006, 1),
          ch("First-home buyer grants", "Help demand, lift prices.", 2, -2, 0, 0.004, 0) ]),
      ev("au_spill", "whip", "A Leadership Spill", "▲",
        "The party room is restless and a rival is counting numbers. The spill could come any morning.",
        [ ch("Confront the rival head-on", "Force a vote on your terms.", 0, 0, -2, 0.0, 1, gmb("partyMgmt","whip", 5,0,6, -9,0,-8)),
          ch("Buy off the plotters", "Promotions for peace.", 1, 0, 3, 0.002, -1),
          ch("Reshuffle to break the bloc", "Scatter the conspirators.", 2, 0, 1, 0.004, 1, gmb("statecraft","pm", 4,0,4, -4,0,-5)) ]),
      ev("au_pacific", "foreign", "The Pacific Step-Up", "🌊",
        "A Pacific neighbour signs a security pact with Beijing on your doorstep.",
        [ ch("Outbid with aid and ties", "Money and mateship to win them back.", 2, -3, 1, 0.008, 3, gmb("statecraft","foreign", 5,-1,2, -4,-4,-3)),
          ch("Lean on them publicly", "Pressure that may backfire.", -2, 0, 1, -0.004, -1),
          ch("Deepen the US alliance", "Anchor harder to Washington.", 1, -1, 1, 0.004, 1) ])
    ],

    /* ======================================================= CANADA ======= */
    canada: [
      ev("ca_quebec", "pm", "The Quebec Question", "⚜",
        "Sovereigntist sentiment stirs again. The province demands more powers, or else.",
        [ ch("Devolve real powers", "Buy unity with autonomy.", 2, -1, -1, 0.006, 2),
          ch("Defend the federation firmly", "One Canada, no special deals.", 0, 0, 2, 0.002, 1, gmb("oratory","pm", 4,0,3, -5,0,-4)),
          ch("Offer recognition, not power", "Symbolism over substance.", 1, 0, 0, 0.002, 0) ]),
      ev("ca_pipeline", "business", "Pipeline or Planet", "⛽",
        "A pipeline would bring billions and western jobs — and torch your climate credibility.",
        [ ch("Approve the pipeline", "Alberta cheers, the coasts revolt.", 2, 5, -3, 0.006, 0),
          ch("Kill it for the climate", "Greens cheer, the west seethes.", -2, -3, 1, -0.004, 2),
          ch("Approve it, fund a green transition", "Buy off both sides at a price.", 1, 1, 0, 0.004, 2, gmb("statecraft","business", 4,4,1, -4,-3,-2)) ]),
      ev("ca_usa", "foreign", "Trouble With Washington", "★",
        "Your largest trading partner threatens tariffs and reopens the trade deal.",
        [ ch("Retaliate dollar-for-dollar", "Stand up to the elephant.", 3, -3, 2, 0.008, 2, gmb("statecraft","foreign", 5,1,2, -4,-5,-3)),
          ch("Negotiate quietly", "Concede a little to keep the border open.", 0, 2, 0, 0.004, 1),
          ch("Diversify trade elsewhere", "Court Europe and Asia.", 1, 0, 0, 0.004, 2) ]),
      ev("ca_reconcile", "justice", "Reconciliation", "§",
        "The discovery of unmarked graves at former schools forces a reckoning with the past.",
        [ ch("A landmark settlement and reforms", "Spend and act on the calls to action.", 3, -3, 0, 0.008, 4, gmb("statecraft","justice", 5,-1,2, -4,-2,-3)),
          ch("An apology and a commission", "Words and process.", 1, 0, 0, 0.002, 1),
          ch("Move on quickly", "Underplay it and pay later.", -4, 1, -1, -0.008, -4) ]),
      ev("ca_health", "health", "Healthcare Under Strain", "✚",
        "ERs are overwhelmed and the provinces demand more federal cash with no strings.",
        [ ch("Fund them, with conditions", "Money for measurable reform.", 3, -3, 0, 0.006, 3, gmb("statecraft","health", 5,-1,2, -4,-3,-3)),
          ch("Hand over the cash, no strings", "Provinces happy, results uncertain.", 2, -4, 1, 0.004, 0),
          ch("Hold firm on the purse", "Fiscal discipline, angry premiers.", -4, 3, -2, -0.006, -1) ]),
      ev("ca_carbon", "chancellor", "The Carbon Tax Fight", "⚡",
        "Your carbon price is popular with economists and toxic on the prairies.",
        [ ch("Defend and rebate it", "Stick with the policy, cut the cheques.", 2, 1, -1, 0.006, 3, gmb("oratory","pm", 4,1,2, -5,-1,-3)),
          ch("Carve out exemptions", "Blunt the policy to blunt the anger.", 1, -1, 1, 0.002, -1),
          ch("Scrap it", "Surrender the signature climate tool.", 3, -2, -2, -0.006, -3) ]),
      ev("ca_immig", "home", "Immigration Targets", "⚓",
        "Record newcomer numbers strain housing and services; cutting them risks the growth story.",
        [ ch("Trim the targets", "Ease the pressure on housing.", 2, -1, 0, 0.006, 0),
          ch("Hold the ambitious levels", "Bet on growth and welcome.", -2, 3, 1, -0.004, 2),
          ch("Tie intake to housing supply", "A clever conditional cap.", 1, 1, 0, 0.004, 2, gmb("statecraft","home", 4,2,2, -3,-2,-2)) ]),
      ev("ca_arctic", "defence", "Arctic Sovereignty", "❄",
        "Melting ice opens the North to Russian and Chinese ambition. Your presence there is thin.",
        [ ch("Invest in northern defence", "Bases, icebreakers, presence.", 1, -4, 1, 0.006, 3),
          ch("Partner with allies", "Share the cost of the cold.", 1, -1, 0, 0.004, 2, gmb("statecraft","foreign", 4,0,2, -3,-2,-2)),
          ch("Prioritise other needs", "The Arctic can wait.", -2, 2, -1, -0.004, -2) ]),
      ev("ca_housing", "business", "The Housing Crisis", "⌂",
        "Home prices in the big cities are among the world's most unaffordable.",
        [ ch("A national building programme", "Federal money for millions of doors.", 4, -3, -1, 0.008, 3, gmb("statecraft","business", 5,3,1, -4,-4,-2)),
          ch("Curb foreign buyers", "A populist, partial fix.", 2, 0, 0, 0.004, 0),
          ch("Leave it to the market", "Trust prices to correct.", -4, 2, -1, -0.006, -2) ]),
      ev("ca_lang", "pm", "The Language Question", "❡",
        "A row over French-language rights flares between Ottawa and a province.",
        [ ch("Defend bilingualism", "Stand for both official languages.", 1, 0, 1, 0.004, 2),
          ch("Accommodate the province", "Flexibility over the federal line.", 0, 0, -1, 0.002, 0),
          ch("Stay out of it", "Let the courts decide.", -1, 0, 0, -0.002, -1) ])
    ],

    /* ======================================================= INDIA ======== */
    india: [
      ev("in_farm", "business", "The Farm Laws", "🌾",
        "Your agricultural reforms bring hundreds of thousands of farmers to the capital's edge for months.",
        [ ch("Repeal the laws", "A humbling but calming retreat.", 4, -3, -2, 0.008, -1),
          ch("Hold firm and negotiate", "Talk while standing your ground.", 0, 1, 1, 0.004, 2, gmb("statecraft","business", 4,3,2, -5,-2,-4)),
          ch("Push the reforms through", "Modernise over the protests.", -3, 4, 0, -0.006, 1) ]),
      ev("in_communal", "home", "Communal Tensions", "☮",
        "Riots flare between communities. The response will define your standing for years.",
        [ ch("Impose order impartially", "Curfew and calm, even-handed.", 2, -1, 1, 0.006, 3, gmb("statecraft","home", 5,0,3, -5,-2,-4)),
          ch("Side with the majority mood", "Popular, and corrosive.", 3, 0, -2, 0.006, -3),
          ch("Lead a reconciliation drive", "Heal at a political cost.", -2, -1, 2, -0.004, 3) ]),
      ev("in_pakistan", "defence", "Across the Line of Control", "⚔",
        "A deadly attack is blamed on militants from across the border. The nation bays for a response.",
        [ ch("Launch a precision strike", "Hit back hard and visibly.", 5, -2, 3, 0.010, 2, gmb("statecraft","defence", 6,-1,3, -7,-3,-4)),
          ch("Apply diplomatic pressure", "Isolate them on the world stage.", 0, 0, 0, 0.004, 3),
          ch("Show restraint", "Refuse to be provoked into war.", -4, 2, -2, -0.006, 1) ]),
      ev("in_reform", "chancellor", "The Next Wave of Reform", "₹",
        "Investors want bold liberalisation; the unions and small traders want protection.",
        [ ch("Big-bang liberalisation", "Open up and chase growth.", 1, 6, -2, 0.008, 2, gmb("statecraft","chancellor", 5,6,1, -5,-5,-3)),
          ch("Gradual, managed opening", "Reform without the shock.", 2, 2, 1, 0.004, 2),
          ch("Protect domestic industry", "Swadeshi over globalisation.", 1, -2, 1, 0.002, 0) ]),
      ev("in_monsoon", "business", "The Monsoon Fails", "☁",
        "A weak monsoon threatens harvests and the livelihoods of hundreds of millions.",
        [ ch("Massive rural support", "Loan waivers and food security.", 5, -5, 1, 0.010, 3),
          ch("Invest in irrigation", "A structural fix for the long term.", 1, -1, 0, 0.004, 3, gmb("statecraft","business", 4,3,1, -3,-3,-2)),
          ch("Manage food stocks tightly", "Technocratic, unglamorous.", -1, 1, 0, 0.0, 0) ]),
      ev("in_china", "defence", "The Himalayan Standoff", "🏔",
        "Troops clash at altitude on the disputed Chinese border. The cabinet wants options.",
        [ ch("Reinforce the frontier", "Match them ridge for ridge.", 2, -4, 2, 0.006, 3, gmb("statecraft","defence", 5,-1,2, -5,-4,-3)),
          ch("De-escalate through talks", "Pull back to avoid catastrophe.", 0, 2, -1, 0.004, 1),
          ch("Hit them economically", "Ban their apps and contracts.", 3, -1, 1, 0.006, 1) ]),
      ev("in_caste", "justice", "Reservation Politics", "§",
        "A powerful community demands quota status. Courts, castes and votes all collide.",
        [ ch("Extend the reservations", "Win the bloc, strain the system.", 3, -1, -2, 0.008, -1),
          ch("Hold the constitutional line", "Defend the cap, brave the backlash.", -2, 0, 1, -0.004, 2, gmb("statecraft","justice", 4,0,3, -4,0,-3)),
          ch("Offer economic criteria instead", "A clever sidestep.", 1, 0, 1, 0.002, 1) ]),
      ev("in_infra", "business", "A Mega-Project", "🏗",
        "A vast new corridor or capital could transform a region — or become a costly white elephant.",
        [ ch("Build it big and fast", "A monument to ambition.", 3, 3, 0, 0.008, 3, gmb("statecraft","business", 6,5,1, -5,-5,-3)),
          ch("A modest, phased version", "Prudence over spectacle.", 1, 1, 1, 0.004, 1),
          ch("Cancel it", "Save the money, lose the dream.", -2, 1, -1, -0.004, -1) ]),
      ev("in_scam", "whip", "A Corruption Scandal", "!",
        "A spectrum or contracts scandal engulfs a senior minister. The opposition smells blood.",
        [ ch("Sack the minister at once", "Decisive distancing.", 2, 0, -3, 0.004, 2),
          ch("Defend and stonewall", "Circle the wagons.", -5, 0, 2, -0.010, -5),
          ch("Order a clean investigation", "Transparency as a weapon.", 0, 0, 0, 0.002, 1, gmb("oratory","pm", 3,0,2, -4,0,-3)) ]),
      ev("in_states", "pm", "Centre Versus States", "▤",
        "Opposition-run states defy a federal scheme, demanding their share and their say.",
        [ ch("Assert federal authority", "Centralise, and chafe the regions.", 1, 1, -2, 0.004, 0, gmb("statecraft","pm", 4,1,2, -4,-1,-4)),
          ch("Cut a cooperative deal", "Share funds for cooperation.", 2, -2, 2, 0.006, 2),
          ch("Bypass them to the people", "Deliver directly, embarrass them.", 0, 0, 0, 0.002, 1) ])
    ],

    /* ======================================================== JAPAN ======= */
    japan: [
      ev("jp_aging", "health", "The Ageing Nation", "⏳",
        "A third of the country is elderly and the workforce shrinks each year. The bill is staggering.",
        [ ch("Raise taxes for elder care", "Honest, unpopular arithmetic.", -5, 5, -1, -0.006, 3),
          ch("Open up to immigration", "Break a taboo to fill the gaps.", -2, 3, -3, -0.004, 2, gmb("statecraft","home", 4,3,2, -4,-2,-4)),
          ch("Automate and raise the retirement age", "Robots and longer careers.", 1, 2, 0, 0.004, 2) ]),
      ev("jp_senkaku", "foreign", "The Senkaku Islands", "🏝",
        "Chinese vessels mass around the disputed islands. A miscalculation could mean war.",
        [ ch("Hold firm with the coast guard", "Presence without provocation.", 2, -1, 2, 0.006, 3, gmb("statecraft","foreign", 5,0,2, -5,-3,-3)),
          ch("Seek a quiet understanding", "Lower the temperature privately.", 0, 2, -1, 0.004, 1),
          ch("Call in the alliance", "Invoke the Americans loudly.", 1, -1, 1, 0.004, 2) ]),
      ev("jp_article9", "defence", "Article 9", "⚔",
        "Pressure builds to revise the pacifist constitution and let Japan defend itself more freely.",
        [ ch("Push constitutional revision", "A historic, divisive crusade.", -1, -1, 3, 0.004, 2, gmb("oratory","pm", 5,0,4, -7,0,-5)),
          ch("Reinterpret, don't revise", "Stretch the meaning quietly.", 1, 0, 0, 0.004, 1),
          ch("Uphold strict pacifism", "Keep the post-war covenant.", 0, 1, -1, 0.002, 1) ]),
      ev("jp_deflation", "chancellor", "Breaking Deflation", "¥",
        "Decades of stagnation linger. The central bank and the markets watch your fiscal nerve.",
        [ ch("A huge stimulus package", "Spend boldly to spark life.", 4, 2, 0, 0.008, 3, gmb("statecraft","chancellor", 5,6,1, -4,-6,-3)),
          ch("Fiscal discipline first", "Tame the world's biggest debt.", -4, 2, 0, -0.006, 1),
          ch("Structural reform", "Shake up a sclerotic economy.", 0, 1, -2, 0.004, 2) ]),
      ev("jp_nuclear", "business", "Restart the Reactors?", "⚡",
        "Years after Fukushima, the reactors sit idle and energy costs bite. The public is wary.",
        [ ch("Restart them under strict rules", "Cheaper power, nervous public.", 1, 4, -2, 0.004, 1, gmb("statecraft","business", 4,4,1, -5,-3,-3)),
          ch("Keep them off, go renewable", "Honour the fear, pay the premium.", 2, -3, 1, 0.004, 2),
          ch("Phase a careful return", "Restart a few, watch closely.", 0, 1, 0, 0.002, 1) ]),
      ev("jp_okinawa", "foreign", "The Okinawa Bases", "★",
        "Locals demand the American bases leave; Washington insists they stay. You're caught between.",
        [ ch("Relocate the base", "A costly compromise for calm.", 2, -3, 0, 0.006, 2, gmb("statecraft","foreign", 4,0,2, -4,-3,-3)),
          ch("Stand by the alliance", "Tokyo backs Washington.", -2, 1, 1, -0.002, 1),
          ch("Press the US for concessions", "Demand a better deal for locals.", 1, 0, 0, 0.004, 1) ]),
      ev("jp_faction", "whip", "Factional Warfare", "▲",
        "The party's factions are at each other's throats over money and succession.",
        [ ch("Balance the factions", "Distribute posts to keep the peace.", 1, 0, 3, 0.002, 0),
          ch("Break the faction system", "A reformer's crusade against your own.", -2, 0, -2, 0.004, 3, gmb("partyMgmt","whip", 5,0,5, -8,0,-7)),
          ch("Side with the biggest faction", "Bank their numbers, make enemies.", 2, 0, -1, 0.004, -2) ]),
      ev("jp_quake", "pm", "The Big One", "🌊",
        "A massive earthquake and tsunami strike. The nation's resilience — and yours — is on trial.",
        [ ch("Lead a flawless response", "Mobilise everything, be everywhere.", 6, -5, 2, 0.012, 4, gmb("statecraft","pm", 6,-2,3, -6,-4,-3)),
          ch("Delegate to the experts", "Stand back, let the system work.", 0, -2, 0, 0.0, 0),
          ch("Rebuild bigger and better", "Turn disaster into renewal.", 3, -3, 1, 0.006, 3) ]),
      ev("jp_birthrate", "health", "The Birthrate Crisis", "👶",
        "Births hit a record low. Without change, the nation will halve within a century.",
        [ ch("Lavish family support", "Cash, childcare, and leave.", 4, -4, 0, 0.008, 3, gmb("statecraft","health", 5,-1,1, -4,-3,-2)),
          ch("Reform the work culture", "Take on the salaryman ethos.", 1, 0, -1, 0.004, 2),
          ch("Accept managed decline", "Plan for a smaller Japan.", -3, 1, 0, -0.006, -1) ]),
      ev("jp_whaling", "foreign", "International Pressure", "🐋",
        "Global outrage mounts over a contentious national practice. Tradition and reputation clash.",
        [ ch("Defend the tradition", "National pride over foreign opinion.", 2, 0, 2, 0.004, -1),
          ch("Quietly wind it down", "Bow to the world, gently.", -1, 0, -1, 0.002, 2, gmb("statecraft","foreign", 3,0,2, -3,0,-2)),
          ch("Defy the international body", "Walk out and carry on.", 1, -1, 1, 0.002, -2) ])
    ],

    /* ================================== ONE-PARTY / AUTHORITARIAN STATE === */
    authoritarian: [
      ev("au_plan", "chancellor", "The Five-Year Plan", "★",
        "The Plan's targets are due. Reality lags the quotas, but the Politburo expects triumph.",
        [ ch("Report glorious overfulfilment", "Inflate the figures, applaud yourself.", 5, -3, 2, 0.008, -2),
          ch("Set realistic, achievable goals", "Honesty the apparatus distrusts.", -2, 4, 0, -0.004, 3, gmb("statecraft","chancellor", 5,6,2, -4,-5,-3)),
          ch("Drive a brutal production push", "Squeeze the people for output.", 1, 5, -3, 0.004, -3) ]),
      ev("au_purge", "whip", "A Question of Loyalty", "⚑",
        "Intelligence whispers of disloyalty among senior cadres. A purge would terrify rivals into line.",
        [ ch("Purge the suspected faction", "Remove them; let fear do the rest.", 2, -1, 5, 0.006, -4, gmb("partyMgmt","whip", 5,0,6, -8,-2,-6)),
          ch("Co-opt them with promotions", "Bind rivals close with privilege.", 1, 0, 3, 0.004, 0),
          ch("Ignore the whispers", "Project confidence, risk a plot.", -2, 0, -3, -0.006, 1) ]),
      ev("au_dissent", "home", "Whispers of Dissent", "✊",
        "Underground pamphlets and small protests appear. Left unchecked, they could spread.",
        [ ch("Crush it without mercy", "Arrests, surveillance, silence.", 1, 0, 2, 0.004, -3, gmb("statecraft","home", 4,0,3, -5,-1,-4)),
          ch("Make a small concession", "Release a little pressure deliberately.", 3, -2, -1, 0.006, 2),
          ch("Stage a managed 'debate'", "Theatre of openness, no real change.", 0, 0, 1, 0.002, -1) ]),
      ev("au_cult", "pm", "The Cult of Personality", "☀",
        "Officials propose statues, portraits and a new title in your honour.",
        [ ch("Embrace the adoration", "Let the image tower over the nation.", 4, -2, 3, 0.006, -3),
          ch("Affect modest reluctance", "Refuse the statues, keep the power.", 1, 1, 1, 0.004, 3),
          ch("Redirect the cult to the Party", "Glorify the movement, not the man.", 0, 1, 2, 0.002, 1) ]),
      ev("au_succession", "leader", "The Succession", "▲",
        "Age and intrigue raise the unspoken question of who comes next. Naming an heir is dangerous either way.",
        [ ch("Anoint a loyal successor", "Stability, and a rival with ambitions.", 1, 1, 2, 0.004, 2, gmb("statecraft","leader", 4,2,4, -5,-1,-5)),
          ch("Keep them all guessing", "Play heirs against each other.", 0, 0, -2, 0.0, 0),
          ch("Eliminate the front-runner", "Remove the threat, chill the court.", 1, -1, 3, 0.002, -4) ]),
      ev("au_famine", "business", "Shortages in the Provinces", "⚙",
        "Harvests have failed and the provinces report hunger. The official story is abundance.",
        [ ch("Quietly import and relieve it", "Save lives, admit nothing.", 3, -4, 0, 0.006, 3, gmb("statecraft","business", 5,2,1, -4,-4,-3)),
          ch("Maintain the export quotas", "Grain for prestige over bread.", -4, 3, 2, -0.008, -4),
          ch("Blame and replace local officials", "Scapegoats for the shortfall.", 1, -1, 1, 0.002, -2) ]),
      ev("au_trial", "justice", "The Show Trial", "§",
        "A captured 'enemy of the people' awaits judgement. The cameras and the world are watching.",
        [ ch("A spectacular public trial", "Confession, conviction, lesson taught.", 2, 0, 3, 0.004, -3, gmb("oratory","justice", 4,0,3, -5,0,-4)),
          ch("A quiet disappearance", "No trial, no martyr, no headlines.", 0, 0, 1, 0.0, -1),
          ch("Surprising clemency", "Mercy as a calculated signal.", 1, 0, -1, 0.004, 2) ]),
      ev("au_sanctions", "foreign", "The World Closes In", "⛓",
        "Foreign powers tighten sanctions over your conduct. The economy feels the squeeze.",
        [ ch("Defiance and self-reliance", "Juche, autarky, pride over plenty.", 2, -4, 3, 0.004, -2),
          ch("Seek a powerful patron", "Trade sovereignty for a lifeline.", 0, 4, -1, 0.004, 1, gmb("statecraft","foreign", 4,5,1, -3,-4,-2)),
          ch("Make limited concessions", "Buy relief with small reforms.", 3, 2, -3, 0.006, 2) ]),
      ev("au_army", "defence", "The Generals Stir", "⚔",
        "The military's loyalty is the foundation of your rule — and its commanders know it.",
        [ ch("Shower them with privilege", "Buy the barracks with budgets.", 1, -4, 4, 0.004, -1),
          ch("Install loyalist commissars", "Watch the watchmen.", 0, 0, 2, 0.002, 1, gmb("statecraft","defence", 4,0,4, -6,-1,-5)),
          ch("Rotate and divide the command", "No general too comfortable.", 1, 0, 1, 0.002, 0) ]),
      ev("au_defector", "foreign", "A High-Profile Defector", "✈",
        "A senior figure has fled abroad and is spilling secrets to a delighted foreign press.",
        [ ch("Denounce them as a traitor", "Discredit, deny, move on.", 1, 0, 2, 0.002, -2),
          ch("Tighten the borders further", "No one else gets out.", -1, -1, 1, -0.002, -2, gmb("statecraft","home", 3,0,3, -4,-1,-3)),
          ch("Lure their family as leverage", "A ruthless quiet pressure.", 0, 0, 1, 0.0, -3) ]),
      ev("au_open", "chancellor", "Reform or Control", "⚖",
        "Pragmatists urge cautious market opening for growth; hardliners warn it invites the end.",
        [ ch("Cautiously open the economy", "Special zones, foreign money, risk.", 2, 6, -3, 0.008, 3, gmb("statecraft","chancellor", 5,7,1, -5,-6,-4)),
          ch("Tighten control instead", "Stability over prosperity.", -1, -2, 4, -0.004, -2),
          ch("Open the economy, not the politics", "Markets in a cage.", 1, 4, 0, 0.006, 1) ])
    ]
  };

  /* which deck governs each electoral system */
  G.GOV_DECK_BY_SYSTEM = {
    fptp_usa_house: "usa", ec_usa_president: "usa",
    pr_dhondt_weimar: "weimar", pr_dhondt_bundestag: "germany",
    trs_france: "france", av_australia: "australia", fptp_canada: "canada",
    fptp_india: "india", fptp_japan: "japan",
    guided_north_korea: "authoritarian", guided_soviet: "authoritarian",
    guided_cuba: "authoritarian", guided_china: "authoritarian"
  };

  /* deck id for a system key (null → UK / default G.EVENTS) */
  G.govDeckFor = function (systemKey) {
    if (!systemKey || systemKey === "fptp_uk") return null;
    return G.GOV_DECK_BY_SYSTEM[systemKey] || null;
  };

  /* the events the current term should draw from */
  G.activeGovDeckEvents = function () {
    var t = G.term;
    var deck = t && t.govDeck;
    if (deck && G.COUNTRY_EVENTS[deck]) return G.COUNTRY_EVENTS[deck];
    return G.EVENTS;
  };
})();
